#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4
bspc config border_radius 11
bspc config window_gap 12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false

#----------------------------
# Border Colors
#----------------------------

bspc config normal_border_color "#546e7a"
bspc config active_border_color "#1b7eab"
bspc config focused_border_color "#1b7eab"
bspc config presel_border_color "#ffffff"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --experimental-backends -b &
feh --bg-fill $HOME/dotfiles/wallpaper/Wallpaper1.png &
$HOME/.config/polybar/launch.sh
dunst &
udiskie &
fcitx5 &
